name: Build, Scan and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: List published files
      run: ls -R ./publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: MTLSExample
        path: ./publish

  scan:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Arti
