name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Update to use Node.js 20

    - name: Set up .NET
      uses: actions/setup-dotnet@v3 # Update to use Node.js 20
      with:
        dotnet-version: '6.0.x' # Use .NET 6.0, which is a supported LTS version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release
